/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ExprCppTree.g
 *     -                            On : 2020-08-26 23:51:10
 *     -                for the parser : ExprCppTreeParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ExprCppTreeParserTokenNames[18+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "DEF",
        (pANTLR3_UINT8) "DIV",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "MOD",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ExprCppTreeParser_expr_return
	expr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_multExpr_return
	multExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_atom_return
	atom    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_defid_sub_return
	defid_sub    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_defid_return
	defid    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_return
	block    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_stmt_return
	block_stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_stmt_return
	stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_prog_return
	prog    (pExprCppTreeParser ctx);
static void	ExprCppTreeParserFree(pExprCppTreeParser ctx);
static void     ExprCppTreeParserReset (pExprCppTreeParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ExprCppTreeParserNewSSD(instream, NULL);
}

/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pExprCppTreeParser) ANTLR3_CALLOC(1, sizeof(ExprCppTreeParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ExprCppTreeParser interface
     */
    ctx->expr	= expr;
    ctx->multExpr	= multExpr;
    ctx->atom	= atom;
    ctx->defid_sub	= defid_sub;
    ctx->defid	= defid;
    ctx->block	= block;
    ctx->block_stmt	= block_stmt;
    ctx->stmt	= stmt;
    ctx->prog	= prog;
    ctx->free			= ExprCppTreeParserFree;
    ctx->reset			= ExprCppTreeParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ExprCppTreeParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ExprCppTreeParserReset (pExprCppTreeParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ExprCppTreeParserFree(pExprCppTreeParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return ExprCppTreeParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr58  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr58_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr58	= { FOLLOW_multExpr_in_expr58_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr62  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr62_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr62	= { FOLLOW_PLUS_in_expr62_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_expr67  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_expr67_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_expr67	= { FOLLOW_MINUS_in_expr67_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr71  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr71_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr71	= { FOLLOW_multExpr_in_expr71_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr105  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr105_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004882) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr105	= { FOLLOW_atom_in_multExpr105_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TIMES_in_multExpr109  */
static	ANTLR3_BITWORD FOLLOW_TIMES_in_multExpr109_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_TIMES_in_multExpr109	= { FOLLOW_TIMES_in_multExpr109_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DIV_in_multExpr114  */
static	ANTLR3_BITWORD FOLLOW_DIV_in_multExpr114_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_DIV_in_multExpr114	= { FOLLOW_DIV_in_multExpr114_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MOD_in_multExpr119  */
static	ANTLR3_BITWORD FOLLOW_MOD_in_multExpr119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_MOD_in_multExpr119	= { FOLLOW_MOD_in_multExpr119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr123  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004882) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr123	= { FOLLOW_atom_in_multExpr123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom158  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom158_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom158	= { FOLLOW_INT_in_atom158_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom166  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom166_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom166	= { FOLLOW_ID_in_atom166_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_atom174  */
static	ANTLR3_BITWORD FOLLOW_16_in_atom174_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_atom174	= { FOLLOW_16_in_atom174_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom177  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom177	= { FOLLOW_expr_in_atom177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_atom179  */
static	ANTLR3_BITWORD FOLLOW_17_in_atom179_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_atom179	= { FOLLOW_17_in_atom179_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_defid_sub192  */
static	ANTLR3_BITWORD FOLLOW_ID_in_defid_sub192_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_defid_sub192	= { FOLLOW_ID_in_defid_sub192_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_defid_sub200  */
static	ANTLR3_BITWORD FOLLOW_ID_in_defid_sub200_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_defid_sub200	= { FOLLOW_ID_in_defid_sub200_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_defid_sub203  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_defid_sub203_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_defid_sub203	= { FOLLOW_ASSIGN_in_defid_sub203_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_defid_sub206  */
static	ANTLR3_BITWORD FOLLOW_expr_in_defid_sub206_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_defid_sub206	= { FOLLOW_expr_in_defid_sub206_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DEF_in_defid212  */
static	ANTLR3_BITWORD FOLLOW_DEF_in_defid212_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_DEF_in_defid212	= { FOLLOW_DEF_in_defid212_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_defid_sub_in_defid215  */
static	ANTLR3_BITWORD FOLLOW_defid_sub_in_defid215_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000C0000) };
static  ANTLR3_BITSET_LIST FOLLOW_defid_sub_in_defid215	= { FOLLOW_defid_sub_in_defid215_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_defid218  */
static	ANTLR3_BITWORD FOLLOW_18_in_defid218_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_defid218	= { FOLLOW_18_in_defid218_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_defid_sub_in_defid221  */
static	ANTLR3_BITWORD FOLLOW_defid_sub_in_defid221_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000C0000) };
static  ANTLR3_BITSET_LIST FOLLOW_defid_sub_in_defid221	= { FOLLOW_defid_sub_in_defid221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_defid225  */
static	ANTLR3_BITWORD FOLLOW_19_in_defid225_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_defid225	= { FOLLOW_19_in_defid225_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_block245  */
static	ANTLR3_BITWORD FOLLOW_20_in_block245_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000311340) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_block245	= { FOLLOW_20_in_block245_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_stmt_in_block247  */
static	ANTLR3_BITWORD FOLLOW_block_stmt_in_block247_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_block_stmt_in_block247	= { FOLLOW_block_stmt_in_block247_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_block249  */
static	ANTLR3_BITWORD FOLLOW_21_in_block249_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_block249	= { FOLLOW_21_in_block249_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_block_stmt263  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_block_stmt263_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000111342) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_block_stmt263	= { FOLLOW_stmt_in_block_stmt263_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt277  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt277_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt277	= { FOLLOW_expr_in_stmt277_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_stmt279  */
static	ANTLR3_BITWORD FOLLOW_19_in_stmt279_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_stmt279	= { FOLLOW_19_in_stmt279_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt281  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt281_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt281	= { FOLLOW_NEWLINE_in_stmt281_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stmt295  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stmt295_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stmt295	= { FOLLOW_ID_in_stmt295_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_stmt297  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_stmt297_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_stmt297	= { FOLLOW_ASSIGN_in_stmt297_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt299  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt299_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt299	= { FOLLOW_expr_in_stmt299_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_stmt301  */
static	ANTLR3_BITWORD FOLLOW_19_in_stmt301_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_stmt301	= { FOLLOW_19_in_stmt301_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt303  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt303_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt303	= { FOLLOW_NEWLINE_in_stmt303_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_defid_in_stmt322  */
static	ANTLR3_BITWORD FOLLOW_defid_in_stmt322_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_defid_in_stmt322	= { FOLLOW_defid_in_stmt322_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt324  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt324_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt324	= { FOLLOW_NEWLINE_in_stmt324_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_stmt336  */
static	ANTLR3_BITWORD FOLLOW_block_in_stmt336_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_stmt336	= { FOLLOW_block_in_stmt336_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt344  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt344_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt344	= { FOLLOW_NEWLINE_in_stmt344_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_prog376  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_prog376_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000111342) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_prog376	= { FOLLOW_stmt_in_prog376_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start expr
 * ExprCppTree.g:16:1: expr : multExpr ( ( PLUS ^| MINUS ^) multExpr )* ;
 */
static ExprCppTreeParser_expr_return
expr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS2;
    pANTLR3_COMMON_TOKEN    MINUS3;
    ExprCppTreeParser_multExpr_return multExpr1;
    #undef	RETURN_TYPE_multExpr1
    #define	RETURN_TYPE_multExpr1 ExprCppTreeParser_multExpr_return

    ExprCppTreeParser_multExpr_return multExpr4;
    #undef	RETURN_TYPE_multExpr4
    #define	RETURN_TYPE_multExpr4 ExprCppTreeParser_multExpr_return

    pANTLR3_BASE_TREE PLUS2_tree;
    pANTLR3_BASE_TREE MINUS3_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS2       = NULL;
    MINUS3       = NULL;
    multExpr1.tree = NULL;

    multExpr4.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS2_tree   = NULL;
    MINUS3_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:16:5: ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* )
        // ExprCppTree.g:16:7: multExpr ( ( PLUS ^| MINUS ^) multExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multExpr_in_expr58);
            multExpr1=multExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multExpr1.tree);

            // ExprCppTree.g:16:16: ( ( PLUS ^| MINUS ^) multExpr )*

            for (;;)
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // ExprCppTree.g:16:17: ( PLUS ^| MINUS ^) multExpr
            	    {
            	        // ExprCppTree.g:16:17: ( PLUS ^| MINUS ^)
            	        {
            	            int alt1=2;
            	            switch ( LA(1) )
            	            {
            	            case PLUS:
            	            	{
            	            		alt1=1;
            	            	}
            	                break;
            	            case MINUS:
            	            	{
            	            		alt1=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 1;
            	                EXCEPTION->state        = 0;


            	                goto ruleexprEx;

            	            }

            	            switch (alt1)
            	            {
            	        	case 1:
            	        	    // ExprCppTree.g:16:18: PLUS ^
            	        	    {
            	        	        PLUS2 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_expr62);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        PLUS2_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS2))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS2_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ExprCppTree.g:16:26: MINUS ^
            	        	    {
            	        	        MINUS3 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_expr67);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        MINUS3_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS3))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS3_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multExpr_in_expr71);
            	        multExpr4=multExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr4.tree);

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multExpr
 * ExprCppTree.g:22:1: multExpr : atom ( ( TIMES ^| DIV ^| MOD ^) atom )* ;
 */
static ExprCppTreeParser_multExpr_return
multExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_multExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    TIMES6;
    pANTLR3_COMMON_TOKEN    DIV7;
    pANTLR3_COMMON_TOKEN    MOD8;
    ExprCppTreeParser_atom_return atom5;
    #undef	RETURN_TYPE_atom5
    #define	RETURN_TYPE_atom5 ExprCppTreeParser_atom_return

    ExprCppTreeParser_atom_return atom9;
    #undef	RETURN_TYPE_atom9
    #define	RETURN_TYPE_atom9 ExprCppTreeParser_atom_return

    pANTLR3_BASE_TREE TIMES6_tree;
    pANTLR3_BASE_TREE DIV7_tree;
    pANTLR3_BASE_TREE MOD8_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    TIMES6       = NULL;
    DIV7       = NULL;
    MOD8       = NULL;
    atom5.tree = NULL;

    atom9.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    TIMES6_tree   = NULL;
    DIV7_tree   = NULL;
    MOD8_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:23:5: ( atom ( ( TIMES ^| DIV ^| MOD ^) atom )* )
        // ExprCppTree.g:23:7: atom ( ( TIMES ^| DIV ^| MOD ^) atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr105);
            atom5=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom5.tree);

            // ExprCppTree.g:23:12: ( ( TIMES ^| DIV ^| MOD ^) atom )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case DIV:
                case MOD:
                case TIMES:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ExprCppTree.g:23:13: ( TIMES ^| DIV ^| MOD ^) atom
            	    {
            	        // ExprCppTree.g:23:13: ( TIMES ^| DIV ^| MOD ^)
            	        {
            	            int alt3=3;
            	            switch ( LA(1) )
            	            {
            	            case TIMES:
            	            	{
            	            		alt3=1;
            	            	}
            	                break;
            	            case DIV:
            	            	{
            	            		alt3=2;
            	            	}
            	                break;
            	            case MOD:
            	            	{
            	            		alt3=3;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 3;
            	                EXCEPTION->state        = 0;


            	                goto rulemultExprEx;

            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // ExprCppTree.g:23:14: TIMES ^
            	        	    {
            	        	        TIMES6 = (pANTLR3_COMMON_TOKEN) MATCHT(TIMES, &FOLLOW_TIMES_in_multExpr109);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        TIMES6_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, TIMES6))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, TIMES6_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ExprCppTree.g:23:23: DIV ^
            	        	    {
            	        	        DIV7 = (pANTLR3_COMMON_TOKEN) MATCHT(DIV, &FOLLOW_DIV_in_multExpr114);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        DIV7_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DIV7))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DIV7_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 3:
            	        	    // ExprCppTree.g:23:30: MOD ^
            	        	    {
            	        	        MOD8 = (pANTLR3_COMMON_TOKEN) MATCHT(MOD, &FOLLOW_MOD_in_multExpr119);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        MOD8_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MOD8))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MOD8_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr123);
            	        atom9=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom9.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start atom
 * ExprCppTree.g:30:1: atom : ( INT | ID | '(' ! expr ')' !);
 */
static ExprCppTreeParser_atom_return
atom(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT10;
    pANTLR3_COMMON_TOKEN    ID11;
    pANTLR3_COMMON_TOKEN    char_literal12;
    pANTLR3_COMMON_TOKEN    char_literal14;
    ExprCppTreeParser_expr_return expr13;
    #undef	RETURN_TYPE_expr13
    #define	RETURN_TYPE_expr13 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE INT10_tree;
    pANTLR3_BASE_TREE ID11_tree;
    pANTLR3_BASE_TREE char_literal12_tree;
    pANTLR3_BASE_TREE char_literal14_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT10       = NULL;
    ID11       = NULL;
    char_literal12       = NULL;
    char_literal14       = NULL;
    expr13.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT10_tree   = NULL;
    ID11_tree   = NULL;
    char_literal12_tree   = NULL;
    char_literal14_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:30:5: ( INT | ID | '(' ! expr ')' !)

            ANTLR3_UINT32 alt5;

            alt5=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt5=1;
            	}
                break;
            case ID:
            	{
            		alt5=2;
            	}
                break;
            case 16:
            	{
            		alt5=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt5)
            {
        	case 1:
        	    // ExprCppTree.g:30:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT10 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom158);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT10_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT10));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT10_tree);


        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:31:7: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID11 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom166);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID11_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID11));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID11_tree);


        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:32:7: '(' ! expr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal12 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_atom174);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom177);
        	        expr13=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr13.tree);

        	        char_literal14 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_atom179);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start defid_sub
 * ExprCppTree.g:35:1: defid_sub : ( ID | ID ^ ASSIGN ! expr );
 */
static ExprCppTreeParser_defid_sub_return
defid_sub(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_defid_sub_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ID15;
    pANTLR3_COMMON_TOKEN    ID16;
    pANTLR3_COMMON_TOKEN    ASSIGN17;
    ExprCppTreeParser_expr_return expr18;
    #undef	RETURN_TYPE_expr18
    #define	RETURN_TYPE_expr18 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE ID15_tree;
    pANTLR3_BASE_TREE ID16_tree;
    pANTLR3_BASE_TREE ASSIGN17_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    ID15       = NULL;
    ID16       = NULL;
    ASSIGN17       = NULL;
    expr18.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    ID15_tree   = NULL;
    ID16_tree   = NULL;
    ASSIGN17_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:35:10: ( ID | ID ^ ASSIGN ! expr )

            ANTLR3_UINT32 alt6;

            alt6=2;

            switch ( LA(1) )
            {
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt6=2;
            			}
            		    break;
            		case 18:
            		case 19:
            			{
            				alt6=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 6;
            		    EXCEPTION->state        = 1;


            		    goto ruledefid_subEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto ruledefid_subEx;

            }

            switch (alt6)
            {
        	case 1:
        	    // ExprCppTree.g:35:12: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID15 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_defid_sub192);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledefid_subEx;
        	        }

        	        ID15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID15));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID15_tree);


        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:36:7: ID ^ ASSIGN ! expr
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID16 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_defid_sub200);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledefid_subEx;
        	        }

        	        ID16_tree = 
        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID16))
        	        ;
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, ID16_tree, root_0));


        	        ASSIGN17 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_defid_sub203);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledefid_subEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_defid_sub206);
        	        expr18=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledefid_subEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr18.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruledefid_subEx; /* Prevent compiler warnings */
    ruledefid_subEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end defid_sub */

/**
 * $ANTLR start defid
 * ExprCppTree.g:37:1: defid : DEF ^ defid_sub ( ',' ! defid_sub )* ';' !;
 */
static ExprCppTreeParser_defid_return
defid(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_defid_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    DEF19;
    pANTLR3_COMMON_TOKEN    char_literal21;
    pANTLR3_COMMON_TOKEN    char_literal23;
    ExprCppTreeParser_defid_sub_return defid_sub20;
    #undef	RETURN_TYPE_defid_sub20
    #define	RETURN_TYPE_defid_sub20 ExprCppTreeParser_defid_sub_return

    ExprCppTreeParser_defid_sub_return defid_sub22;
    #undef	RETURN_TYPE_defid_sub22
    #define	RETURN_TYPE_defid_sub22 ExprCppTreeParser_defid_sub_return

    pANTLR3_BASE_TREE DEF19_tree;
    pANTLR3_BASE_TREE char_literal21_tree;
    pANTLR3_BASE_TREE char_literal23_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    DEF19       = NULL;
    char_literal21       = NULL;
    char_literal23       = NULL;
    defid_sub20.tree = NULL;

    defid_sub22.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    DEF19_tree   = NULL;
    char_literal21_tree   = NULL;
    char_literal23_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:37:6: ( DEF ^ defid_sub ( ',' ! defid_sub )* ';' !)
        // ExprCppTree.g:37:8: DEF ^ defid_sub ( ',' ! defid_sub )* ';' !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            DEF19 = (pANTLR3_COMMON_TOKEN) MATCHT(DEF, &FOLLOW_DEF_in_defid212);
            if  (HASEXCEPTION())
            {
                goto ruledefidEx;
            }

            DEF19_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DEF19))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DEF19_tree, root_0));


            FOLLOWPUSH(FOLLOW_defid_sub_in_defid215);
            defid_sub20=defid_sub(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledefidEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, defid_sub20.tree);

            // ExprCppTree.g:37:23: ( ',' ! defid_sub )*

            for (;;)
            {
                int alt7=2;
                switch ( LA(1) )
                {
                case 18:
                	{
                		alt7=1;
                	}
                    break;

                }

                switch (alt7)
                {
            	case 1:
            	    // ExprCppTree.g:37:24: ',' ! defid_sub
            	    {
            	        char_literal21 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_defid218);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledefidEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_defid_sub_in_defid221);
            	        defid_sub22=defid_sub(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledefidEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, defid_sub22.tree);

            	    }
            	    break;

            	default:
            	    goto loop7;	/* break out of the loop */
            	    break;
                }
            }
            loop7: ; /* Jump out to here if this rule does not match */


            char_literal23 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_defid225);
            if  (HASEXCEPTION())
            {
                goto ruledefidEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledefidEx; /* Prevent compiler warnings */
    ruledefidEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end defid */

/**
 * $ANTLR start block
 * ExprCppTree.g:42:1: block : '{' block_stmt '}' -> ^( BLOCK block_stmt ) ;
 */
static ExprCppTreeParser_block_return
block(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal24;
    pANTLR3_COMMON_TOKEN    char_literal26;
    ExprCppTreeParser_block_stmt_return block_stmt25;
    #undef	RETURN_TYPE_block_stmt25
    #define	RETURN_TYPE_block_stmt25 ExprCppTreeParser_block_stmt_return

    pANTLR3_BASE_TREE char_literal24_tree;
    pANTLR3_BASE_TREE char_literal26_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_20;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_21;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_block_stmt;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal24       = NULL;
    char_literal26       = NULL;
    block_stmt25.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal24_tree   = NULL;
    char_literal26_tree   = NULL;

    stream_20   = NULL;
    #define CREATE_stream_20  if (stream_20 == NULL) {stream_20 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 20"); } 
    stream_21   = NULL;
    #define CREATE_stream_21  if (stream_21 == NULL) {stream_21 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 21"); } 
    stream_block_stmt   = NULL;
    #define CREATE_stream_block_stmt  if (stream_block_stmt == NULL) {stream_block_stmt = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule block_stmt"); }

    retval.tree  = NULL;

    {
        // ExprCppTree.g:42:6: ( '{' block_stmt '}' -> ^( BLOCK block_stmt ) )
        // ExprCppTree.g:42:8: '{' block_stmt '}'
        {
            char_literal24 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_block245);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_20; stream_20->add(stream_20, char_literal24, NULL);


            FOLLOWPUSH(FOLLOW_block_stmt_in_block247);
            block_stmt25=block_stmt(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }

            CREATE_stream_block_stmt; stream_block_stmt->add(stream_block_stmt, block_stmt25.tree, NULL);

            char_literal26 = (pANTLR3_COMMON_TOKEN) MATCHT(21, &FOLLOW_21_in_block249);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_21; stream_21->add(stream_21, char_literal26, NULL);


            /* AST REWRITE
             * elements          : block_stmt
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 42:27: -> ^( BLOCK block_stmt )
            	{
            	    // ExprCppTree.g:42:30: ^( BLOCK block_stmt )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, BLOCK, (pANTLR3_UINT8)"BLOCK")
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_block_stmt == NULL ? NULL : stream_block_stmt->nextTree(stream_block_stmt));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblockEx; /* Prevent compiler warnings */
    ruleblockEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_20 != NULL) stream_20->free(stream_20);
        if (stream_21 != NULL) stream_21->free(stream_21);
        if (stream_block_stmt != NULL) stream_block_stmt->free(stream_block_stmt);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block */

/**
 * $ANTLR start block_stmt
 * ExprCppTree.g:43:1: block_stmt : ( stmt )* ;
 */
static ExprCppTreeParser_block_stmt_return
block_stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt27;
    #undef	RETURN_TYPE_stmt27
    #define	RETURN_TYPE_stmt27 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt27.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ExprCppTree.g:43:11: ( ( stmt )* )
        // ExprCppTree.g:43:13: ( stmt )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ExprCppTree.g:43:13: ( stmt )*

            for (;;)
            {
                int alt8=2;
                switch ( LA(1) )
                {
                case DEF:
                case ID:
                case INT:
                case NEWLINE:
                case 16:
                case 20:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8)
                {
            	case 1:
            	    // ExprCppTree.g:43:13: stmt
            	    {
            	        FOLLOWPUSH(FOLLOW_stmt_in_block_stmt263);
            	        stmt27=stmt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleblock_stmtEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, stmt27.tree);

            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblock_stmtEx; /* Prevent compiler warnings */
    ruleblock_stmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block_stmt */

/**
 * $ANTLR start stmt
 * ExprCppTree.g:46:1: stmt : ( expr ';' NEWLINE -> expr | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | defid NEWLINE -> defid | block | NEWLINE ->);
 */
static ExprCppTreeParser_stmt_return
stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal29;
    pANTLR3_COMMON_TOKEN    NEWLINE30;
    pANTLR3_COMMON_TOKEN    ID31;
    pANTLR3_COMMON_TOKEN    ASSIGN32;
    pANTLR3_COMMON_TOKEN    char_literal34;
    pANTLR3_COMMON_TOKEN    NEWLINE35;
    pANTLR3_COMMON_TOKEN    NEWLINE37;
    pANTLR3_COMMON_TOKEN    NEWLINE39;
    ExprCppTreeParser_expr_return expr28;
    #undef	RETURN_TYPE_expr28
    #define	RETURN_TYPE_expr28 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr33;
    #undef	RETURN_TYPE_expr33
    #define	RETURN_TYPE_expr33 ExprCppTreeParser_expr_return

    ExprCppTreeParser_defid_return defid36;
    #undef	RETURN_TYPE_defid36
    #define	RETURN_TYPE_defid36 ExprCppTreeParser_defid_return

    ExprCppTreeParser_block_return block38;
    #undef	RETURN_TYPE_block38
    #define	RETURN_TYPE_block38 ExprCppTreeParser_block_return

    pANTLR3_BASE_TREE char_literal29_tree;
    pANTLR3_BASE_TREE NEWLINE30_tree;
    pANTLR3_BASE_TREE ID31_tree;
    pANTLR3_BASE_TREE ASSIGN32_tree;
    pANTLR3_BASE_TREE char_literal34_tree;
    pANTLR3_BASE_TREE NEWLINE35_tree;
    pANTLR3_BASE_TREE NEWLINE37_tree;
    pANTLR3_BASE_TREE NEWLINE39_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_19;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_defid;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal29       = NULL;
    NEWLINE30       = NULL;
    ID31       = NULL;
    ASSIGN32       = NULL;
    char_literal34       = NULL;
    NEWLINE35       = NULL;
    NEWLINE37       = NULL;
    NEWLINE39       = NULL;
    expr28.tree = NULL;

    expr33.tree = NULL;

    defid36.tree = NULL;

    block38.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal29_tree   = NULL;
    NEWLINE30_tree   = NULL;
    ID31_tree   = NULL;
    ASSIGN32_tree   = NULL;
    char_literal34_tree   = NULL;
    NEWLINE35_tree   = NULL;
    NEWLINE37_tree   = NULL;
    NEWLINE39_tree   = NULL;

    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_19   = NULL;
    #define CREATE_stream_19  if (stream_19 == NULL) {stream_19 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 19"); } 
    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_defid   = NULL;
    #define CREATE_stream_defid  if (stream_defid == NULL) {stream_defid = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule defid"); }
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:46:5: ( expr ';' NEWLINE -> expr | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | defid NEWLINE -> defid | block | NEWLINE ->)

            ANTLR3_UINT32 alt9;

            alt9=5;

            switch ( LA(1) )
            {
            case INT:
            case 16:
            	{
            		alt9=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt9=2;
            			}
            		    break;
            		case DIV:
            		case MINUS:
            		case MOD:
            		case PLUS:
            		case TIMES:
            		case 19:
            			{
            				alt9=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 9;
            		    EXCEPTION->state        = 2;


            		    goto rulestmtEx;

            		}

            	}
                break;
            case DEF:
            	{
            		alt9=3;
            	}
                break;
            case 20:
            	{
            		alt9=4;
            	}
                break;
            case NEWLINE:
            	{
            		alt9=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 9;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt9)
            {
        	case 1:
        	    // ExprCppTree.g:46:7: expr ';' NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_stmt277);
        	        expr28=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr28.tree, NULL);

        	        char_literal29 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_stmt279);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_19; stream_19->add(stream_19, char_literal29, NULL);


        	        NEWLINE30 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt281);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE30, NULL);


        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 46:24: -> expr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:47:7: ID ASSIGN expr ';' NEWLINE
        	    {
        	        ID31 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stmt295);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID31, NULL);


        	        ASSIGN32 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_stmt297);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN32, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt299);
        	        expr33=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr33.tree, NULL);

        	        char_literal34 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_stmt301);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_19; stream_19->add(stream_19, char_literal34, NULL);


        	        NEWLINE35 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt303);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE35, NULL);


        	        /* AST REWRITE
        	         * elements          : ID, ASSIGN, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 47:34: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // ExprCppTree.g:47:37: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:48:7: defid NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_defid_in_stmt322);
        	        defid36=defid(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_defid; stream_defid->add(stream_defid, defid36.tree, NULL);

        	        NEWLINE37 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt324);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE37, NULL);


        	        /* AST REWRITE
        	         * elements          : defid
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 48:21: -> defid
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_defid == NULL ? NULL : stream_defid->nextTree(stream_defid));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 4:
        	    // ExprCppTree.g:49:7: block
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_block_in_stmt336);
        	        block38=block(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, block38.tree);

        	    }
        	    break;
        	case 5:
        	    // ExprCppTree.g:50:7: NEWLINE
        	    {
        	        NEWLINE39 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt344);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE39, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 50:15: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_19 != NULL) stream_19->free(stream_19);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_defid != NULL) stream_defid->free(stream_defid);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start prog
 * ExprCppTree.g:55:1: prog : ( stmt )+ ;
 */
static ExprCppTreeParser_prog_return
prog(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt40;
    #undef	RETURN_TYPE_stmt40
    #define	RETURN_TYPE_stmt40 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt40.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ExprCppTree.g:56:5: ( ( stmt )+ )
        // ExprCppTree.g:56:7: ( stmt )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ExprCppTree.g:56:7: ( stmt )+
            {
                int cnt10=0;

                for (;;)
                {
                    int alt10=2;
            	switch ( LA(1) )
            	{
            	case DEF:
            	case ID:
            	case INT:
            	case NEWLINE:
            	case 16:
            	case 20:
            		{
            			alt10=1;
            		}
            	    break;

            	}

            	switch (alt10)
            	{
            	    case 1:
            	        // ExprCppTree.g:56:8: stmt
            	        {
            	            FOLLOWPUSH(FOLLOW_stmt_in_prog376);
            	            stmt40=stmt(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, stmt40.tree);

            	            {

            	                        #ifdef INFOMSG
            	                        pANTLR3_STRING s = (stmt40.tree)->toStringTree((stmt40.tree));
            	                             assert(s->chars);
            	                             printf(" haizei tree %s\n", s->chars);
            	                            fflush(stdout);
            	                        #endif    
            	                        
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt10 >= 1 )
            		{
            		    goto loop10;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt10++;
                }
                loop10: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
